services:
  server:
    image: ghcr.io/mohammadlashkari/blog/blog
    container_name: blog
    restart: unless-stopped
    ports:
      - "2026:2026"
    env_file:
      - .env
    environment:
      ENV: "production"
      PORT: "2026"
      DB_PATH: "/data/blog.db"
      SITE_URL: "https://mohammadlashkari.com"
      LIMITER_RPS: "10"
      LIMITER_BURST: "20"
      LIMITER_ENABLE: "true"
      LOCAL_CONTENT_PATH: "/data/blog-content"
      REMOTE_CONTENT_PATH: "https://github.com/mohammadlashkari/blog-content.git"
      MAIN_BRANCH_NAME: "master"
      CONTENT_FILENAME: "index.md"
      TOKEN_VERSION: "1"
    volumes:
      - ./data:/data
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:2026/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
