// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"
)

type RssItem struct {
	ID          int64      `json:"id"`
	FeedName    string     `json:"feed_name"`
	FeedUrl     string     `json:"feed_url"`
	Guid        string     `json:"guid"`
	Link        string     `json:"link"`
	Title       string     `json:"title"`
	Description *string    `json:"description"`
	Categories  *string    `json:"categories"`
	PublishedAt *time.Time `json:"published_at"`
	FetchedAt   time.Time  `json:"fetched_at"`
	Status      string     `json:"status"`
}
