// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package store

import (
	"context"
	"time"
)

const checkFeedExists = `-- name: CheckFeedExists :one
SELECT EXISTS(
    SELECT 1 FROM rss_items WHERE feed_url = ?
)
`

func (q *Queries) CheckFeedExists(ctx context.Context, feedUrl string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkFeedExists, feedUrl)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createRssItem = `-- name: CreateRssItem :exec
INSERT INTO rss_items (
    feed_name, feed_url, guid, link, title, description, published_at, status, categories
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT(feed_url, guid) DO NOTHING
`

type CreateRssItemParams struct {
	FeedName    string     `json:"feed_name"`
	FeedUrl     string     `json:"feed_url"`
	Guid        string     `json:"guid"`
	Link        string     `json:"link"`
	Title       string     `json:"title"`
	Description *string    `json:"description"`
	PublishedAt *time.Time `json:"published_at"`
	Status      string     `json:"status"`
	Categories  *string    `json:"categories"`
}

func (q *Queries) CreateRssItem(ctx context.Context, arg CreateRssItemParams) error {
	_, err := q.db.ExecContext(ctx, createRssItem,
		arg.FeedName,
		arg.FeedUrl,
		arg.Guid,
		arg.Link,
		arg.Title,
		arg.Description,
		arg.PublishedAt,
		arg.Status,
		arg.Categories,
	)
	return err
}

const deleteByFeedUR = `-- name: DeleteByFeedUR :exec
DELETE FROM rss_items
WHERE feed_url = ?
`

func (q *Queries) DeleteByFeedUR(ctx context.Context, feedUrl string) error {
	_, err := q.db.ExecContext(ctx, deleteByFeedUR, feedUrl)
	return err
}

const getItemsByStatus = `-- name: GetItemsByStatus :many
SELECT id, feed_name, feed_url, guid, link, title, description, categories, published_at, fetched_at, status FROM rss_items
WHERE status = ?
ORDER BY published_at DESC NULLS LAST
`

func (q *Queries) GetItemsByStatus(ctx context.Context, status string) ([]RssItem, error) {
	rows, err := q.db.QueryContext(ctx, getItemsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RssItem
	for rows.Next() {
		var i RssItem
		if err := rows.Scan(
			&i.ID,
			&i.FeedName,
			&i.FeedUrl,
			&i.Guid,
			&i.Link,
			&i.Title,
			&i.Description,
			&i.Categories,
			&i.PublishedAt,
			&i.FetchedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItemStatus = `-- name: UpdateItemStatus :exec
UPDATE rss_items
SET status = ? 
WHERE id = ?
`

type UpdateItemStatusParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateItemStatus(ctx context.Context, arg UpdateItemStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateItemStatus, arg.Status, arg.ID)
	return err
}
