// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	CheckFeedExists(ctx context.Context, feedUrl string) (bool, error)
	CreateRssItem(ctx context.Context, arg CreateRssItemParams) error
	DeleteByFeedUR(ctx context.Context, feedUrl string) error
	GetItemsByStatus(ctx context.Context, arg GetItemsByStatusParams) ([]RssItem, error)
	ToggleSavedStatus(ctx context.Context, arg ToggleSavedStatusParams) error
	UpdateItemStatus(ctx context.Context, arg UpdateItemStatusParams) error
}

var _ Querier = (*Queries)(nil)
