// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"
)

type Post struct {
	ID          int64      `json:"id"`
	Filename    string     `json:"filename"`
	Title       string     `json:"title"`
	Slug        string     `json:"slug"`
	CoverImage  *string    `json:"cover_image"`
	Language    Language   `json:"language"`
	IsFavorite  bool       `json:"is_favorite"`
	Version     int64      `json:"version"`
	CreatedAt   time.Time  `json:"created_at"`
	PublishedAt *time.Time `json:"published_at"`
	UpdatedAt   *time.Time `json:"updated_at"`
}

type PostTag struct {
	PostID int64 `json:"post_id"`
	TagID  int64 `json:"tag_id"`
}

type Tag struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}
