// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package ui

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func initWasm() templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_initWasm_bcb2`,
		Function: `function __templ_initWasm_bcb2(){const go = new Go();
    WebAssembly.instantiateStreaming(
        fetch("/static/bin/life.wasm"),
        go.importObject,
    ).then((result) => {
        go.run(result.instance);
    });
}`,
		Call:       templ.SafeScript(`__templ_initWasm_bcb2`),
		CallInline: templ.SafeScriptInline(`__templ_initWasm_bcb2`),
	}
}

func GameOfLifeEmbed() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<figure class=\"mt-8 mb-10\"><canvas id=\"board\" class=\"block aspect-square w-full rounded-md border border-line bg-paper\"></canvas><figcaption class=\"mt-3 flex flex-wrap items-center justify-between gap-3\"><button id=\"pauseButton\" class=\"cursor-pointer rounded-md border border-line px-3 py-1.5 text-[0.85rem] hover:border-accent hover:text-accent\">Pause</button></figcaption></figure><script src=\"/static/wasm_exec.js\"></script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = initWasm().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
