// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package post

import (
	"context"
	"strings"
	"time"
)

const addPostTag = `-- name: AddPostTag :exec
INSERT OR IGNORE INTO post_tags (post_id, tag_id)
VALUES (?, ?)
`

type AddPostTagParams struct {
	PostID int64 `json:"post_id"`
	TagID  int64 `json:"tag_id"`
}

func (q *Queries) AddPostTag(ctx context.Context, arg AddPostTagParams) error {
	_, err := q.db.ExecContext(ctx, addPostTag, arg.PostID, arg.TagID)
	return err
}

const deletePostTags = `-- name: DeletePostTags :exec
DELETE FROM post_tags WHERE post_id = ?
`

func (q *Queries) DeletePostTags(ctx context.Context, postID int64) error {
	_, err := q.db.ExecContext(ctx, deletePostTags, postID)
	return err
}

const listPosts = `-- name: ListPosts :many
SELECT id, title, slug, cover_image, language, is_favorite, content_hash, version, created_at, published_at, updated_at
FROM posts
WHERE (
    published_at IS NOT NULL 
    OR CAST(?1 AS BOOLEAN) = TRUE
)
ORDER BY published_at DESC
`

func (q *Queries) ListPosts(ctx context.Context, includeAll bool) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, listPosts, includeAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.CoverImage,
			&i.Language,
			&i.IsFavorite,
			&i.ContentHash,
			&i.Version,
			&i.CreatedAt,
			&i.PublishedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsByTag = `-- name: ListPostsByTag :many
SELECT DISTINCT posts.id, posts.title, posts.slug, posts.cover_image, posts.language, posts.is_favorite, posts.content_hash, posts.version, posts.created_at, posts.published_at, posts.updated_at
FROM posts
JOIN post_tags post_tags ON posts.id = post_tags.post_id
JOIN tags ON post_tags.tag_id = tags.id
WHERE tags.name IN (/*SLICE:tag_names*/?)
AND (
    posts.published_at IS NOT NULL 
    OR CAST(?2 AS BOOLEAN) = TRUE
)
ORDER BY posts.published_at DESC
`

type ListPostsByTagParams struct {
	TagNames   []string `json:"tag_names"`
	IncludeAll bool     `json:"include_all"`
}

func (q *Queries) ListPostsByTag(ctx context.Context, arg ListPostsByTagParams) ([]Post, error) {
	query := listPostsByTag
	var queryParams []interface{}
	if len(arg.TagNames) > 0 {
		for _, v := range arg.TagNames {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:tag_names*/?", strings.Repeat(",?", len(arg.TagNames))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:tag_names*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.IncludeAll)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.CoverImage,
			&i.Language,
			&i.IsFavorite,
			&i.ContentHash,
			&i.Version,
			&i.CreatedAt,
			&i.PublishedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT id, name FROM tags
`

func (q *Queries) ListTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const postByID = `-- name: PostByID :one
SELECT id, title, slug, cover_image, language, is_favorite, content_hash, version, created_at, published_at, updated_at FROM posts 
WHERE id = ?
AND (
    published_at IS NOT NULL 
    OR CAST(? AS BOOLEAN) = TRUE
)
`

type PostByIDParams struct {
	ID         int64 `json:"id"`
	IncludeAll bool  `json:"include_all"`
}

func (q *Queries) PostByID(ctx context.Context, arg PostByIDParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, postByID, arg.ID, arg.IncludeAll)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.CoverImage,
		&i.Language,
		&i.IsFavorite,
		&i.ContentHash,
		&i.Version,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const postBySlug = `-- name: PostBySlug :one
SELECT id, title, slug, cover_image, language, is_favorite, content_hash, version, created_at, published_at, updated_at FROM posts
WHERE slug = ?
AND (
    published_at IS NOT NULL 
    OR CAST(? AS BOOLEAN) = TRUE
)
`

type PostBySlugParams struct {
	Slug       string `json:"slug"`
	IncludeAll bool   `json:"include_all"`
}

func (q *Queries) PostBySlug(ctx context.Context, arg PostBySlugParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, postBySlug, arg.Slug, arg.IncludeAll)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.CoverImage,
		&i.Language,
		&i.IsFavorite,
		&i.ContentHash,
		&i.Version,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const tagsByPostID = `-- name: TagsByPostID :many
SELECT tags.id, tags.name
FROM tags
JOIN post_tags ON post_tags.tag_id = tags.id
WHERE post_tags.post_id = ?
ORDER BY tags.name
`

func (q *Queries) TagsByPostID(ctx context.Context, postID int64) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, tagsByPostID, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPost = `-- name: UpsertPost :one
INSERT INTO posts (
  title,
  slug,
  cover_image,
  language,
  published_at,
  content_hash
)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(slug) DO UPDATE SET
  title = excluded.title,
  cover_image = excluded.cover_image,
  language = excluded.language,
  published_at = excluded.published_at,
  content_hash = excluded.content_hash,
  version = posts.version + 1,
  updated_at = CURRENT_TIMESTAMP
RETURNING id, title, slug, cover_image, language, is_favorite, content_hash, version, created_at, published_at, updated_at
`

type UpsertPostParams struct {
	Title       string     `json:"title"`
	Slug        string     `json:"slug"`
	CoverImage  *string    `json:"cover_image"`
	Language    Language   `json:"language"`
	PublishedAt *time.Time `json:"published_at"`
	ContentHash string     `json:"content_hash"`
}

func (q *Queries) UpsertPost(ctx context.Context, arg UpsertPostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, upsertPost,
		arg.Title,
		arg.Slug,
		arg.CoverImage,
		arg.Language,
		arg.PublishedAt,
		arg.ContentHash,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.CoverImage,
		&i.Language,
		&i.IsFavorite,
		&i.ContentHash,
		&i.Version,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTag = `-- name: UpsertTag :one
INSERT INTO tags (name)
VALUES (?)
ON CONFLICT(name) DO UPDATE SET name = excluded.name
RETURNING id, name
`

func (q *Queries) UpsertTag(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, upsertTag, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
