// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package post

import (
	"context"
)

type Querier interface {
	ListPosts(ctx context.Context, includeAll bool) ([]Post, error)
	ListPostsByTag(ctx context.Context, arg ListPostsByTagParams) ([]Post, error)
	ListTags(ctx context.Context) ([]Tag, error)
	PostByID(ctx context.Context, arg PostByIDParams) (Post, error)
	PostBySlug(ctx context.Context, arg PostBySlugParams) (Post, error)
	TagsByPostID(ctx context.Context, postID int64) ([]Tag, error)
}

var _ Querier = (*Queries)(nil)
