// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package post

import (
	"context"
)

type Querier interface {
	AddPostTag(ctx context.Context, arg AddPostTagParams) error
	DeletePostTags(ctx context.Context, postID int64) error
	DeletePosts(ctx context.Context, slugs []string) error
	ListPosts(ctx context.Context, includeAll bool) ([]Post, error)
	ListPostsByTag(ctx context.Context, arg ListPostsByTagParams) ([]Post, error)
	ListTags(ctx context.Context) ([]Tag, error)
	ListTagsForPost(ctx context.Context, postID int64) ([]Tag, error)
	PostByID(ctx context.Context, arg PostByIDParams) (Post, error)
	PostBySlug(ctx context.Context, arg PostBySlugParams) (Post, error)
	RemovePostTagsByName(ctx context.Context, arg RemovePostTagsByNameParams) error
	UpsertPost(ctx context.Context, arg UpsertPostParams) (int64, error)
	UpsertTag(ctx context.Context, name string) (int64, error)
}

var _ Querier = (*Queries)(nil)
