// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package post

import (
	"context"
)

const listPosts = `-- name: ListPosts :many
SELECT id, filename, title, slug, cover_image, language, is_favorite, version, created_at, published_at, updated_at
FROM posts
WHERE (
    published_at IS NOT NULL 
    OR CAST(?1 AS BOOLEAN) = TRUE
)
ORDER BY published_at DESC
`

func (q *Queries) ListPosts(ctx context.Context, includeAll bool) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, listPosts, includeAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.Title,
			&i.Slug,
			&i.CoverImage,
			&i.Language,
			&i.IsFavorite,
			&i.Version,
			&i.CreatedAt,
			&i.PublishedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT id, name, slug FROM tags
`

func (q *Queries) ListTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const postByID = `-- name: PostByID :one
SELECT id, filename, title, slug, cover_image, language, is_favorite, version, created_at, published_at, updated_at FROM posts 
WHERE id = ?
AND (
    published_at IS NOT NULL 
    OR CAST(? AS BOOLEAN) = TRUE
)
`

type PostByIDParams struct {
	ID         int64 `json:"id"`
	IncludeAll bool  `json:"include_all"`
}

func (q *Queries) PostByID(ctx context.Context, arg PostByIDParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, postByID, arg.ID, arg.IncludeAll)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.Title,
		&i.Slug,
		&i.CoverImage,
		&i.Language,
		&i.IsFavorite,
		&i.Version,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const postBySlug = `-- name: PostBySlug :one
SELECT id, filename, title, slug, cover_image, language, is_favorite, version, created_at, published_at, updated_at FROM posts
WHERE slug = ?
AND (
    published_at IS NOT NULL 
    OR CAST(? AS BOOLEAN) = TRUE
)
`

type PostBySlugParams struct {
	Slug       string `json:"slug"`
	IncludeAll bool   `json:"include_all"`
}

func (q *Queries) PostBySlug(ctx context.Context, arg PostBySlugParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, postBySlug, arg.Slug, arg.IncludeAll)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.Title,
		&i.Slug,
		&i.CoverImage,
		&i.Language,
		&i.IsFavorite,
		&i.Version,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const postsByTagSlug = `-- name: PostsByTagSlug :many
SELECT posts.id, posts.filename, posts.title, posts.slug, posts.cover_image, posts.language, posts.is_favorite, posts.version, posts.created_at, posts.published_at, posts.updated_at
FROM posts
JOIN post_tags post_tags ON posts.id = post_tags.post_id
JOIN tags ON post_tags.tag_id = tags.id
WHERE tags.slug = ?
AND (
    posts.published_at IS NOT NULL 
    OR CAST(? AS BOOLEAN) = TRUE
)
ORDER BY posts.published_at DESC
`

type PostsByTagSlugParams struct {
	Slug       string `json:"slug"`
	IncludeAll bool   `json:"include_all"`
}

func (q *Queries) PostsByTagSlug(ctx context.Context, arg PostsByTagSlugParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, postsByTagSlug, arg.Slug, arg.IncludeAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.Title,
			&i.Slug,
			&i.CoverImage,
			&i.Language,
			&i.IsFavorite,
			&i.Version,
			&i.CreatedAt,
			&i.PublishedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tagsByPostID = `-- name: TagsByPostID :many
SELECT tags.id, tags.name, tags.slug
FROM tags
JOIN post_tags ON post_tags.tag_id = tags.id
WHERE post_tags.post_id = ?
ORDER BY tags.name
`

func (q *Queries) TagsByPostID(ctx context.Context, postID int64) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, tagsByPostID, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
